# Generated by Django 5.1 on 2024-08-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_content_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="courses.subject",
            ),
            preserve_default=False,
        ),
    ]
